### ISSUE TITLE
Error on msg arrive, Error: messageRawPayload can not find payload for [object Object]

### ISSUE THREAD

**Issue by Samurais** [wechaty/wechaty-puppet-gitter#3]
# packages
```
    "wechaty": "0.30.23",
    "wechaty-puppet-gitter": "^0.4.6"
```

# code

```
  const puppet = new PuppetGitter({ token: config.gitter.token });
  const bot = new Wechaty({ puppet });

  bot.on("error", (e) => {
    console.log("Bot", "error: %s", e);
  });

  bot.on("message", async (m) => {
    try {
      debug("message: %j", m);
      if (m.self()) {
        return;
      }
      //   await brain.handle(bot.self().name(), m);
    } catch (e) {
      console.error("Bot", "on(message) exception: %s", e);
    }
  });

  await bot.start();
  console.log("Bot started.");
```

![image](https://user-images.githubusercontent.com/3538629/92990563-0cb9b380-f510-11ea-80c9-965cb22d318e.png)

# reproduce error

send message from gitter.im with another account.

![image](https://user-images.githubusercontent.com/3538629/92990593-3541ad80-f510-11ea-8905-b872c9d92491.png)

error trace
```
15:48:18 INFO Wechaty <Puppet#0<PuppetGitter>()>() start() v0.30.23 is starting...
Bot started.
PuppetGitter messageRawPayload(%s) { messageId: '5f5c7d5a603d0b37f4283640' }
Unhandled rejection (promise:  Promise {
  <rejected> Error: messageRawPayload can not find payload for [object Object]
      at PuppetGitter.messageRawPayload (/Users/hain/chatopera/chatopera-gitter-sample/gitter/app/node_modules/wechaty-puppet-gitter/dist/src/puppet-gitter.js:343:15)
      at process._tickCallback (internal/process/next_tick.js:68:7) } , reason:  Error: messageRawPayload can not find payload for [object Object]
    at PuppetGitter.messageRawPayload (/Users/hain/chatopera/chatopera-gitter-sample/gitter/app/node_modules/wechaty-puppet-gitter/dist/src/puppet-gitter.js:343:15)
    at process._tickCallback (internal/process/next_tick.js:68:7) ).
PuppetGitter messageRawPayload(%s) { messageId: '5f5c7dccd993b837e05ae38f' }
Unhandled rejection (promise:  Promise {
  <rejected> Error: messageRawPayload can not find payload for [object Object]
      at PuppetGitter.messageRawPayload (/Users/hain/chatopera/chatopera-gitter-sample/gitter/app/node_modules/wechaty-puppet-gitter/dist/src/puppet-gitter.js:343:15)
      at process._tickCallback (internal/process/next_tick.js:68:7) } , reason:  Error: messageRawPayload can not find payload for [object Object]
    at PuppetGitter.messageRawPayload (/Users/hain/chatopera/chatopera-gitter-sample/gitter/app/node_modules/wechaty-puppet-gitter/dist/src/puppet-gitter.js:343:15)
    at process._tickCallback (internal/process/next_tick.js:68:7) ).
```

**Comment by Samurais** [comment]
node  版本 10.21.x,  因为有其他依赖，不能使用 node 更高级版本。

**Comment by huan** [comment]
Could you please paste the full log message by setting the WECHATY_LOG=verbose?
